# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/oezeakachi/Prometheus-and-Grafana-monitoring-stack.git
      targetRevision: main
      ref: prometheus-config
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: 19.7.2
      helm:
        values: |
            server:
              service:
                type: LoadBalancer

              persistentVolume:
                enabled: true # Enable persistence for the Prometheus server
                size: 50Gi    # Specify the desired volume size (e.g., 50 Gigabytes)
                storageClass: gp3 # ⭐ Referencing the 'gp3' StorageClass you've defined

            alertmanager:
              persistentVolume:
                enabled: true
                size: 10Gi # Alertmanager usually needs less storage than Prometheus server
                storageClass: gp3 # Ensure this matches your existing StorageClass name
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  
# ############################## END OF prometheus.yaml ####################################